---
title: "R Notebook"
output: html_notebook
---

Question 3:

Question 5:

a)
```{r}

library(rstan)
library(ggplot2)

stan_code <- '
data {
  real y;
}

parameters {
  real<lower=0> lambda;
}

model {
  lambda ~ gamma(3, 1);
  y ~ exponential(lambda);
}
'

stan_model <- stan_model(model_code = stan_code)

data_list <- list(y = 4)

posterior <- sampling(stan_model, data = data_list, chains = 4, iter = 10000)

```
b)

```{r}
traceplot(posterior, inc_warmup = FALSE)
```

c)
```{r}
# Extract the chains from the posterior object
chains <- as.array(posterior)

# Set the number of lags for autocorrelation
num_lags <- 20

# Calculate autocorrelation for each chain
autocorr <- lapply(chains, function(chain) acf(chain, lag.max = num_lags, plot = FALSE)$acf)

# Plot the autocorrelation for each chain

# Plot the autocorrelation for each chain
plot(0, type = "n", xlim = c(0, num_lags), ylim = c(-1, 1), xlab = "Lag", ylab = "Autocorrelation", main = "Autocorrelation Plot for Chains")
colors <- rainbow(length(chains))
for (i in seq_along(chains)) {
  chain <- na.omit(chains[[i]])
  chain_ts <- ts(chain)
  autocorr_chain <- acf(chain_ts, lag.max = num_lags, plot = FALSE)$acf
  lines(0:num_lags, autocorr_chain, col = colors[i], type = "l")
}
legend("topright", legend = 1:length(chains), col = colors, lty = 1, title = "Chain")
```


